<?php
$pizza = "";
$today = date('Y');
echo "<br>";
$today1 = date('w');
$today2 = date("F j , Y , g:i a");
$today3 = date("j , n , Y");
$today4 = date("Ymd");
$today4 = date('h-i-s , j-m-y , it is w day ');
$today5 = date('\i\t \i\s \t\h\e jS \d\a\y');
$today6 = date("D M j G:i:s T Y");
$today7 = date('H:m:s \m \i\s \m\o\n\t\h');
$today8 = date("H:i:s");
$today9 = date("Y-m-d H:i:s");
echo $today;
echo "<br>";
echo "<br>";
echo $today1;
echo "<br>";
echo "<br>";
echo $today2;
echo "<br>";
echo "<br>";
echo $today3;
echo "<br>";
echo "<br>";
echo $today4;
echo "<br>";
echo "<br>";
echo $today5;
echo "<br>";
echo "<br>";
echo $today6;
echo "<br>";
echo "<br>";
echo $today7;
echo "<br>";
echo "<br>";
echo $today8;
echo "<br>";
echo "<br>";
echo $today9;
echo "<br>";
echo "<br>";